In [1]:
import pandas as pd
import numpy as np

In [2]:
path_enem = 'D:/000000001_ENEM/DADOS_PROCESSADOS/'
path_escolas = 'D:/000000001_ENEM/ESCOLAS/'

In [3]:
enem = pd.read_csv(path_enem+'enem_completo.csv', sep = ';', encoding = 'ISO-8859-1',low_memory=False)

In [4]:
enem.count()

CO_ESCOLA                   629662
CO_MUNICIPIO_RESIDENCIA     629662
CO_UF_ESC                   629662
IN_TREINEIRO                629662
NO_MUNICIPIO_ESC            629662
                             ...  
nome_concorrente            629662
cod_concorrente             629662
cod_entidade_concorrente    629662
ind_concorrente              23728
chave                       629662
Length: 70, dtype: int64

In [5]:
escolas = pd.read_csv(path_escolas+'geral_escolas.csv', sep = ';', encoding = 'ISO-8859-1',low_memory=False)

In [6]:
enem_escolas = pd.merge (enem, escolas, left_on = 'chave', right_on = 'chave', how = 'left')

In [7]:
enem_escolas.to_csv(path_enem + 'base_enem_completa_sem trat.csv', sep = ';', encoding = 'ISO-8859-1')

In [8]:
enem_escolas[['CO_ESCOLA', 'CO_ENTIDADE']].count()

CO_ESCOLA      629662
CO_ENTIDADE    629184
dtype: int64

In [9]:
vazios = pd.DataFrame({'Tipos':enem_escolas.dtypes, 'NaN':enem_escolas.isna().sum(),'Total':enem_escolas.count()}).sort_values('NaN', ascending = False)

In [10]:
enem_escolas.columns.values

array(['CO_ESCOLA', 'CO_MUNICIPIO_RESIDENCIA', 'CO_UF_ESC',
       'IN_TREINEIRO', 'NO_MUNICIPIO_ESC', 'NU_ANO', 'NU_IDADE',
       'NU_INSCRICAO', 'NU_NOTA_CH', 'NU_NOTA_CN', 'NU_NOTA_COMP1',
       'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4', 'NU_NOTA_COMP5',
       'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO', 'Q001', 'Q002',
       'Q003', 'Q004', 'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010',
       'Q011', 'Q012', 'Q013', 'Q014', 'Q015', 'Q016', 'Q017', 'Q018',
       'Q019', 'Q020', 'Q021', 'Q022', 'Q023', 'Q024', 'Q025',
       'SG_UF_ESC', 'SG_UF_RESIDENCIA', 'TP_ANO_CONCLUIU', 'TP_COR_RACA',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_ENSINO', 'TP_ESCOLA',
       'TP_ESTADO_CIVIL', 'TP_LINGUA', 'TP_LOCALIZACAO_ESC',
       'TP_NACIONALIDADE', 'TP_PRESENCA_CH', 'TP_PRESENCA_CN',
       'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'TP_SEXO', 'TP_SIT_FUNC_ESC',
       'TP_STATUS_REDACAO', 'TP_ST_CONCLUSAO', 'nome_entidade_rede',
       'cod_entidade_rede', 'ind_rede', 'nome_concorrente'

In [11]:
enem_escolas['TP_ESTADO_CIVIL'].unique()

array([ 0., nan,  1.,  2.,  3.,  4.])

In [12]:
a = 'TP_ESTADO_CIVIL'
enem_escolas[a].fillna('Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 0, value = 'Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Solteiro', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Casado/Tem companheiro(a)', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Divorciado(a)/Desquitado(a)/Separado(a)', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Viúvo(a)', inplace = True)

In [13]:
enem_escolas['TP_ESTADO_CIVIL'].unique()

array(['Não informado', 'Solteiro', 'Casado/Tem companheiro(a)',
       'Divorciado(a)/Desquitado(a)/Separado(a)', 'Viúvo(a)'],
      dtype=object)

In [14]:
enem_escolas['TP_COR_RACA'].unique()

array([1, 3, 2, 0, 4, 6, 5], dtype=int64)

In [15]:
a = 'TP_COR_RACA'
enem_escolas[a].fillna('ND', inplace = True)
enem_escolas[a].replace(to_replace = 0, value = 'ND', inplace = True) ## Não declarado
enem_escolas[a].replace(to_replace = 1, value = 'Branca', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Preta', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Parda', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Amarela', inplace = True)
enem_escolas[a].replace(to_replace = 5, value = 'Indígena', inplace = True)
enem_escolas[a].replace(to_replace = 6, value = 'ND', inplace = True) ## Não dispõe da informação

In [16]:
enem_escolas['TP_COR_RACA'].unique()

array(['Branca', 'Parda', 'Preta', 'ND', 'Amarela', 'Indígena'],
      dtype=object)

In [17]:
enem_escolas['TP_NACIONALIDADE'].unique()

array([1, 2, 4, 0, 3], dtype=int64)

In [18]:
a = 'TP_NACIONALIDADE'
enem_escolas[a].fillna('Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 0, value = 'Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Brasileiro(a)', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Brasileiro(a) Naturalizado(a)', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Estrangeiro(a)', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Brasileiro(a) Nato(a), nascido(a) no exterior', inplace = True)


In [19]:
enem_escolas['TP_NACIONALIDADE'].unique()

array(['Brasileiro(a)', 'Brasileiro(a) Naturalizado(a)',
       'Brasileiro(a) Nato(a), nascido(a) no exterior', 'Não informado',
       'Estrangeiro(a)'], dtype=object)

In [20]:
enem_escolas['TP_ST_CONCLUSAO'].unique()

array([2, 4, 3], dtype=int64)

In [21]:
a = 'TP_ST_CONCLUSAO'
enem_escolas[a].fillna('Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Já concluí o Ensino Médio', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Estou cursando e concluirei o Ensino Médio no ano corrente', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Estou cursando e concluirei o Ensino Médio após o ano corrente', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Não concluí e não estou cursando o Ensino Médio', inplace = True)

In [22]:
enem_escolas['TP_ST_CONCLUSAO'].unique()

array(['Estou cursando e concluirei o Ensino Médio no ano corrente',
       'Não concluí e não estou cursando o Ensino Médio',
       'Estou cursando e concluirei o Ensino Médio após o ano corrente'],
      dtype=object)

In [23]:
enem_escolas['TP_ESCOLA'].unique()

array([2, 3, 1, 4], dtype=int64)

In [24]:
a = 'TP_ESCOLA'
enem_escolas[a].fillna('Não Respondeu', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Não Respondeu', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Pública', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Privada', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Exterior', inplace = True)

In [25]:
enem_escolas['TP_ESCOLA'].unique()

array(['Pública', 'Privada', 'Não Respondeu', 'Exterior'], dtype=object)

In [26]:
enem_escolas['TP_ENSINO'].unique()

array([ 1.,  3.,  2., nan])

In [27]:
a = 'TP_ENSINO'
enem_escolas[a].fillna('Não Respondeu', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Ensino Regular', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Educação Especial - Modalidade Substitutiva', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Educação de Jovens e Adultos', inplace = True)

In [28]:
enem_escolas['TP_ENSINO'].unique()

array(['Ensino Regular', 'Educação de Jovens e Adultos',
       'Educação Especial - Modalidade Substitutiva', 'Não Respondeu'],
      dtype=object)

In [29]:
enem_escolas['IN_TREINEIRO'].unique()

array([0, 1], dtype=int64)

In [30]:
a = 'IN_TREINEIRO'
enem_escolas[a].fillna('Não Respondeu', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Sim', inplace = True)
enem_escolas[a].replace(to_replace = 0, value = 'Não', inplace = True)

In [31]:
enem_escolas['IN_TREINEIRO'].unique()

array(['Não', 'Sim'], dtype=object)

In [32]:
enem_escolas['TP_DEPENDENCIA_ADM_ESC'].unique()

array([2., 4., 3., 1.])

In [33]:
a = 'TP_DEPENDENCIA_ADM_ESC'
enem_escolas[a].fillna('Não Respondeu', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Federal', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Estadual', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Municipal', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Privada', inplace = True)


In [34]:
enem_escolas['TP_DEPENDENCIA_ADM_ESC'].unique()

array(['Estadual', 'Privada', 'Municipal', 'Federal'], dtype=object)

In [35]:
enem_escolas['TP_LOCALIZACAO_ESC'].unique()

array([1., 2.])

In [36]:
a = 'TP_LOCALIZACAO_ESC'
enem_escolas[a].fillna('Não Respondeu', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Urbana', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Rural', inplace = True)

In [37]:
enem_escolas['TP_LOCALIZACAO_ESC'].unique()

array(['Urbana', 'Rural'], dtype=object)

In [38]:
enem_escolas['TP_SIT_FUNC_ESC'].unique()

array([ 1.,  2., nan,  3.,  4.])

In [39]:
a = 'TP_SIT_FUNC_ESC'
enem_escolas[a].fillna('Não Informado', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Em atividade', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Paralisada', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Extinta', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Escola extinta em anos anteriores', inplace = True)

In [40]:
enem_escolas['TP_SIT_FUNC_ESC'].unique()

array(['Em atividade', 'Paralisada', 'Não Informado', 'Extinta',
       'Escola extinta em anos anteriores'], dtype=object)

In [41]:
enem_escolas['TP_PRESENCA_CN'].unique()

array([ 1.,  0.,  2., nan])

In [42]:
enem_escolas['TP_PRESENCA_CH'].unique()

array([ 1.,  0.,  2., nan])

In [43]:
enem_escolas['TP_PRESENCA_LC'].unique()

array([ 1.,  0.,  2., nan])

In [44]:
enem_escolas['TP_PRESENCA_MT'].unique()

array([ 1.,  0.,  2., nan])

In [45]:
colunas = ['TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC','TP_PRESENCA_MT']
for c in colunas:
    enem_escolas[c].fillna('Não informado', inplace = True)
    enem_escolas[c].replace(to_replace = 0, value = 'Faltou à prova', inplace = True)
    enem_escolas[c].replace(to_replace = 1, value = 'Presente na prova', inplace = True)
    enem_escolas[c].replace(to_replace = 2, value = 'Eliminado na prova', inplace = True)

In [46]:
enem_escolas['TP_PRESENCA_CN'].unique()

array(['Presente na prova', 'Faltou à prova', 'Eliminado na prova',
       'Não informado'], dtype=object)

In [47]:
enem_escolas['TP_LINGUA'].unique()

array([1, 0], dtype=int64)

In [48]:
a = 'TP_LINGUA'
enem_escolas[a].fillna('Não Informado', inplace = True)
enem_escolas[a].replace(to_replace = 0, value = 'Inglês', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Espanhol', inplace = True)

In [49]:
enem_escolas['TP_LINGUA'].unique()

array(['Espanhol', 'Inglês'], dtype=object)

In [50]:
enem_escolas['TP_STATUS_REDACAO'].unique()

array([ 1.,  4.,  6.,  5.,  7., 98.,  3.,  8.,  2.,  9., nan])

In [51]:
a = 'TP_STATUS_REDACAO'
enem_escolas[a].fillna('Não declarado', inplace = True)
enem_escolas[a].replace(to_replace = 1, value = 'Sem problemas', inplace = True)
enem_escolas[a].replace(to_replace = 2, value = 'Anulada', inplace = True)
enem_escolas[a].replace(to_replace = 3, value = 'Cópia texto motivador', inplace = True)
enem_escolas[a].replace(to_replace = 4, value = 'Em branco', inplace = True)
enem_escolas[a].replace(to_replace = 5, value = 'Fere Direitos Humanos', inplace = True)
enem_escolas[a].replace(to_replace = 6, value = 'Fuga ao tema', inplace = True)
enem_escolas[a].replace(to_replace = 7, value = 'Não atendimento ao tipo', inplace = True)
enem_escolas[a].replace(to_replace = 8, value = 'Texto insuficiente', inplace = True)
enem_escolas[a].replace(to_replace = 9, value = 'Parte desconectada', inplace = True)
enem_escolas[a].replace(to_replace = 98, value = 'Não atendimento ao item 2.2.5 do edital do exame.', inplace = True)

In [52]:
enem_escolas['TP_STATUS_REDACAO'].unique()

array(['Sem problemas', 'Em branco', 'Fuga ao tema',
       'Fere Direitos Humanos', 'Não atendimento ao tipo',
       'Não atendimento ao item 2.2.5 do edital do exame.',
       'Cópia texto motivador', 'Texto insuficiente', 'Anulada',
       'Parte desconectada', 'Não declarado'], dtype=object)

In [53]:
## Q001 - Até que série seu pai, ou o homem responsável por você, estudou?
## Q002 - Até que série sua mãe, ou a mulher responsável por você, estudou?
## Q003 - A partir da apresentação de algumas ocupações divididas em grupos ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação do seu pai ou do homem responsável por você. (Se ele não estiver trabalhando, escolha uma ocupação pensando no último trabalho dele).
## Q004 - A partir da apresentação de algumas ocupações divididas em grupos ordenados, indique o grupo que contempla a ocupação mais próxima da ocupação da sua mãe ou da mulher responsável por você. (Se ela não estiver trabalhando, escolha uma ocupação pensando no último trabalho dela).
## Q005 - Incluindo você, quantas pessoas moram atualmente em sua residência?
## Q006 - Qual é a renda mensal de sua família? (Some a sua renda com a dos seus familiares.)
## Q007 - Em sua residência trabalha empregado(a) doméstico(a)?
## Q008 - Na sua residência tem banheiro?
## Q009 - Na sua residência tem quartos para dormir?
## Q010 - Na sua residência tem carro?
## Q011 - Na sua residência tem motocicleta?
## Q012 - Na sua residência tem geladeira?
## Q013 - Na sua residência tem freezer (independente ou segunda porta da geladeira)?
## Q014 - Na sua residência tem máquina de lavar roupa? (o tanquinho NÃO deve ser considerado)
## Q015 - Na sua residência tem máquina de secar roupa (independente ou em conjunto com a máquina de lavar roupa)?
## Q016 - Na sua residência tem forno micro-ondas?
## Q017 - Na sua residência tem máquina de lavar louça?
## Q018 - Na sua residência tem aspirador de pó?
## Q019 - Na sua residência tem televisão em cores?
## Q020 - Na sua residência tem aparelho de DVD?
## Q021 - Na sua residência tem TV por assinatura?
## Q022 - Na sua residência tem telefone celular?
## Q023 - Na sua residência tem telefone fixo?
## Q024 - Na sua residência tem computador?
## Q025 - Na sua residência tem acesso à Internet?


In [54]:
enem_escolas['Q001'].unique()

array(['C', 'D', 'B', 'F', 'E', 'H', 'G', 'A', nan], dtype=object)

In [55]:
enem_escolas['Q002'].unique()

array(['B', 'D', 'E', 'F', 'C', 'G', 'H', nan, 'A'], dtype=object)

In [56]:
q = ['Q001','Q002']
for a in q:
    enem_escolas[a].fillna('Não informado', inplace = True)
    enem_escolas[a].replace(to_replace = 'A', value = 'Nunca estudou', inplace = True)
    enem_escolas[a].replace(to_replace = 'B', value = 'Não completou a 4ª série/5º ano do Ensino Fundamental', inplace = True)
    enem_escolas[a].replace(to_replace = 'C', value = 'Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do Ensino Fundamental', inplace = True)
    enem_escolas[a].replace(to_replace = 'D', value = 'Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio', inplace = True)
    enem_escolas[a].replace(to_replace = 'E', value = 'Completou o Ensino Médio, mas não completou a Faculdade', inplace = True)
    enem_escolas[a].replace(to_replace = 'F', value = 'Completou a Faculdade, mas não completou a Pós-graduação', inplace = True)
    enem_escolas[a].replace(to_replace = 'G', value = 'Completou a Pós-graduação', inplace = True)
    enem_escolas[a].replace(to_replace = 'H', value = 'Não sei.', inplace = True)

In [57]:
enem_escolas['Q001'].unique()

array(['Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do Ensino Fundamental',
       'Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio',
       'Não completou a 4ª série/5º ano do Ensino Fundamental',
       'Completou a Faculdade, mas não completou a Pós-graduação',
       'Completou o Ensino Médio, mas não completou a Faculdade',
       'Não sei.', 'Completou a Pós-graduação', 'Nunca estudou',
       'Não informado'], dtype=object)

In [58]:
enem_escolas['Q002'].unique()

array(['Não completou a 4ª série/5º ano do Ensino Fundamental',
       'Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio',
       'Completou o Ensino Médio, mas não completou a Faculdade',
       'Completou a Faculdade, mas não completou a Pós-graduação',
       'Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do Ensino Fundamental',
       'Completou a Pós-graduação', 'Não sei.', 'Não informado',
       'Nunca estudou'], dtype=object)

In [59]:
##['Q003','Q004']
## Grupo 1: Lavradora, agricultora sem empregados, bóia fria, criadora de animais (gado, porcos, galinhas, ovelhas, cavalos etc.), apicultora, pescadora, lenhadora, seringueira, extrativista.
## Grupo 2: Diarista, empregada doméstica, cuidadora de idosos, babá, cozinheira (em casas particulares), motorista particular, jardineira, faxineira de empresas e prédios, vigilante, porteira, carteira, office-boy, vendedora, caixa, atendente de loja, auxiliar administrativa, recepcionista, servente de pedreiro, repositora de mercadoria.
## Grupo 3: Padeira, cozinheira industrial ou em restaurantes, sapateira, costureira, joalheira, torneira mecânica, operadora de máquinas, soldadora, operária de fábrica, trabalhadora da mineração, pedreira, pintora, eletricista, encanadora, motorista, caminhoneira, taxista.
## Grupo 4: Professora (de ensino fundamental ou médio, idioma, música, artes etc.), técnica (de enfermagem, contabilidade, eletrônica etc.), policial, militar de baixa patente (soldado, cabo, sargento), corretora de imóveis, supervisora, gerente, mestre de obras, pastora, microempresária (proprietária de empresa com menos de 10 empregados), pequena comerciante, pequena proprietária de terras, trabalhadora autônoma ou por conta própria.
## Grupo 5: Médica, engenheira, dentista, psicóloga, economista, advogada, juíza, promotora, defensora, delegada, tenente, capitã, coronel, professora universitária, diretora em empresas públicas ou privadas, política, proprietária de empresas com mais de 10 empregados.
## Não sei.


In [60]:
enem_escolas['Q003'].unique()

array(['C', 'D', 'E', 'B', 'A', 'F', nan], dtype=object)

In [61]:
enem_escolas['Q004'].unique()

array(['B', 'C', 'D', 'F', 'A', 'E', nan], dtype=object)

In [62]:
q = ['Q003','Q004']
for a in q:
    enem_escolas[a].fillna('Não informado', inplace = True)
    enem_escolas[a].replace(to_replace = 'A', value = 'Grupo 1', inplace = True)
    enem_escolas[a].replace(to_replace = 'B', value = 'Grupo 2', inplace = True)
    enem_escolas[a].replace(to_replace = 'C', value = 'Grupo 3', inplace = True)
    enem_escolas[a].replace(to_replace = 'D', value = 'Grupo 4', inplace = True)
    enem_escolas[a].replace(to_replace = 'E', value = 'Grupo 5', inplace = True)
    enem_escolas[a].replace(to_replace = 'F', value = 'Não sei.', inplace = True)

In [63]:
enem_escolas['Q003'].unique()

array(['Grupo 3', 'Grupo 4', 'Grupo 5', 'Grupo 2', 'Grupo 1', 'Não sei.',
       'Não informado'], dtype=object)

In [64]:
enem_escolas['Q004'].unique()

array(['Grupo 2', 'Grupo 3', 'Grupo 4', 'Não sei.', 'Grupo 1', 'Grupo 5',
       'Não informado'], dtype=object)

In [65]:
enem_escolas['Q005'].unique()

array([ 3.,  5.,  4.,  2.,  7.,  6.,  1., 10., nan,  8.,  9., 11., 13.,
       14., 12., 20., 19., 18., 16., 17., 15.])

In [66]:
enem_escolas['Q005'].fillna('Não informado', inplace = True)

In [67]:
enem_escolas['Q006'].unique()

array(['B', 'C', 'G', 'N', 'E', 'D', 'K', 'I', 'F', 'J', 'H', 'L', 'O',
       'Q', nan, 'A', 'M', 'P'], dtype=object)

In [68]:
a = 'Q006'
enem_escolas[a].fillna('Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 'A', value = 'Nenhuma renda', inplace = True)
enem_escolas[a].replace(to_replace = 'B', value = 'Até R$ 998,00', inplace = True)
enem_escolas[a].replace(to_replace = 'C', value = 'De R$ 998,01 até R$ 1.497,00', inplace = True)
enem_escolas[a].replace(to_replace = 'D', value = 'De R$ 1.497,01 até R$ 1.996,00', inplace = True)
enem_escolas[a].replace(to_replace = 'E', value = 'De R$ 1.996,01 até R$ 2.495,00', inplace = True)
enem_escolas[a].replace(to_replace = 'F', value = 'De R$ 2.495,01 até R$ 2.994,00', inplace = True)
enem_escolas[a].replace(to_replace = 'G', value = 'De R$ 2.994,01 até R$ 3.992,00', inplace = True)
enem_escolas[a].replace(to_replace = 'H', value = 'De R$ 3.992,01 até R$ 4.990,00', inplace = True)
enem_escolas[a].replace(to_replace = 'I', value = 'De R$ 4.990,01 até R$ 5.988,00', inplace = True)
enem_escolas[a].replace(to_replace = 'J', value = 'De R$ 5.988,01 até R$ 6.986,00', inplace = True)
enem_escolas[a].replace(to_replace = 'K', value = 'De R$ 6.986,01 até R$ 7.984,00', inplace = True)
enem_escolas[a].replace(to_replace = 'L', value = 'De R$ 7.984,01 até R$ 8.982,00', inplace = True)
enem_escolas[a].replace(to_replace = 'M', value = 'De R$ 8.982,01 até R$ 9.980,00', inplace = True)
enem_escolas[a].replace(to_replace = 'N', value = 'De R$ 9.980,01 até R$ 11.976,00', inplace = True)
enem_escolas[a].replace(to_replace = 'O', value = 'De R$ 11.976,01 até R$ 14.970,00', inplace = True)
enem_escolas[a].replace(to_replace = 'P', value = 'De R$ 14.970,01 até R$ 19.960,00', inplace = True)
enem_escolas[a].replace(to_replace = 'Q', value = 'Mais de R$ 19.960,00.', inplace = True)


In [69]:
enem_escolas['Q006'].unique()

array(['Até R$ 998,00', 'De R$ 998,01 até R$ 1.497,00',
       'De R$ 2.994,01 até R$ 3.992,00',
       'De R$ 9.980,01 até R$ 11.976,00',
       'De R$ 1.996,01 até R$ 2.495,00', 'De R$ 1.497,01 até R$ 1.996,00',
       'De R$ 6.986,01 até R$ 7.984,00', 'De R$ 4.990,01 até R$ 5.988,00',
       'De R$ 2.495,01 até R$ 2.994,00', 'De R$ 5.988,01 até R$ 6.986,00',
       'De R$ 3.992,01 até R$ 4.990,00', 'De R$ 7.984,01 até R$ 8.982,00',
       'De R$ 11.976,01 até R$ 14.970,00', 'Mais de R$ 19.960,00.',
       'Não informado', 'Nenhuma renda', 'De R$ 8.982,01 até R$ 9.980,00',
       'De R$ 14.970,01 até R$ 19.960,00'], dtype=object)

In [70]:
enem_escolas['Q007'].unique()

array(['A', 'D', 'B', nan, 'C'], dtype=object)

In [71]:
a = 'Q007'
enem_escolas[a].fillna('Não informado', inplace = True)
enem_escolas[a].replace(to_replace = 'A', value = 'Não', inplace = True)
enem_escolas[a].replace(to_replace = 'B', value = 'Sim, um ou dois dias por semana', inplace = True)
enem_escolas[a].replace(to_replace = 'C', value = 'Sim, três ou quatro dias por semana', inplace = True)
enem_escolas[a].replace(to_replace = 'D', value = 'Sim, pelo menos cinco dias por semana', inplace = True)

In [72]:
enem_escolas['Q007'].unique()

array(['Não', 'Sim, pelo menos cinco dias por semana',
       'Sim, um ou dois dias por semana', 'Não informado',
       'Sim, três ou quatro dias por semana'], dtype=object)

In [73]:
q = ['Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014','Q015', 'Q016', 'Q017','Q019', 'Q022', 'Q024']
for a in q:
    print(a)
    print(enem_escolas[a].unique())

Q008
['B' 'C' 'D' 'E' nan 'A']
Q009
['D' 'C' 'E' 'B' nan 'A']
Q010
['A' 'B' 'C' nan 'D' 'E']
Q011
['A' 'B' nan 'C' 'E' 'D']
Q012
['B' 'C' 'D' 'A' nan 'E']
Q013
['B' 'A' 'E' nan 'C' 'D']
Q014
['A' 'B' nan 'C' 'D' 'E']
Q015
['A' 'B' nan 'C' 'D' 'E']
Q016
['A' 'B' 'C' nan 'E' 'D']
Q017
['A' 'B' nan 'C' 'D' 'E']
Q019
['C' 'D' 'B' 'E' 'A' nan]
Q022
['D' 'C' 'E' 'B' 'A' nan]
Q024
['B' 'C' 'D' 'A' 'E' nan]


In [74]:
q = ['Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014','Q015', 'Q016', 'Q017','Q019', 'Q022', 'Q024']
for a in q:
    enem_escolas[a].fillna('Não informado', inplace = True)
    enem_escolas[a].replace(to_replace = 'A', value = 'Não', inplace = True)
    enem_escolas[a].replace(to_replace = 'B', value = 'Sim, um', inplace = True)
    enem_escolas[a].replace(to_replace = 'C', value = 'Sim, dois', inplace = True)
    enem_escolas[a].replace(to_replace = 'D', value = 'Sim, três', inplace = True)
    enem_escolas[a].replace(to_replace = 'E', value = 'Sim, quatro ou mais', inplace = True)

In [75]:
q = ['Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013', 'Q014','Q015', 'Q016', 'Q017','Q019', 'Q022', 'Q024']
for a in q:
    print(a)
    print(enem_escolas[a].unique())

Q008
['Sim, um' 'Sim, dois' 'Sim, três' 'Sim, quatro ou mais' 'Não informado'
 'Não']
Q009
['Sim, três' 'Sim, dois' 'Sim, quatro ou mais' 'Sim, um' 'Não informado'
 'Não']
Q010
['Não' 'Sim, um' 'Sim, dois' 'Não informado' 'Sim, três'
 'Sim, quatro ou mais']
Q011
['Não' 'Sim, um' 'Não informado' 'Sim, dois' 'Sim, quatro ou mais'
 'Sim, três']
Q012
['Sim, um' 'Sim, dois' 'Sim, três' 'Não' 'Não informado'
 'Sim, quatro ou mais']
Q013
['Sim, um' 'Não' 'Sim, quatro ou mais' 'Não informado' 'Sim, dois'
 'Sim, três']
Q014
['Não' 'Sim, um' 'Não informado' 'Sim, dois' 'Sim, três'
 'Sim, quatro ou mais']
Q015
['Não' 'Sim, um' 'Não informado' 'Sim, dois' 'Sim, três'
 'Sim, quatro ou mais']
Q016
['Não' 'Sim, um' 'Sim, dois' 'Não informado' 'Sim, quatro ou mais'
 'Sim, três']
Q017
['Não' 'Sim, um' 'Não informado' 'Sim, dois' 'Sim, três'
 'Sim, quatro ou mais']
Q019
['Sim, dois' 'Sim, três' 'Sim, um' 'Sim, quatro ou mais' 'Não'
 'Não informado']
Q022
['Sim, três' 'Sim, dois' 'Sim, quatro ou mais' 'S

In [76]:
q = [ 'Q018', 'Q020', 'Q021','Q023','Q025']
for a in q:
    print(a)
    print(enem_escolas[a].unique())

Q018
['A' 'B' nan]
Q020
['B' 'A' nan]
Q021
['A' 'B' nan]
Q023
['B' 'A' nan]
Q025
['B' 'A' nan]


In [77]:
q = [ 'Q018', 'Q020', 'Q021','Q023','Q025']
for a in q:
    enem_escolas[a].fillna('Não informado', inplace = True)
    enem_escolas[a].replace(to_replace = 'A', value = 'Não', inplace = True)
    enem_escolas[a].replace(to_replace = 'B', value = 'Sim', inplace = True)   

In [78]:
q = [ 'Q018', 'Q020', 'Q021','Q023','Q025']
for a in q:
    print(a)
    print(enem_escolas[a].unique())

Q018
['Não' 'Sim' 'Não informado']
Q020
['Sim' 'Não' 'Não informado']
Q021
['Não' 'Sim' 'Não informado']
Q023
['Sim' 'Não' 'Não informado']
Q025
['Sim' 'Não' 'Não informado']


In [79]:
q = [  'ind_rede', 'ind_concorrente','IN_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO','IN_TABLET_ALUNO', 'IN_INTERNET',
     'IN_INTERNET_ALUNOS', 'IN_INTERNET_ADMINISTRATIVO','IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_COMUNIDADE',
     'IN_ACESSO_INTERNET_COMPUTADOR', 'IN_ACES_INTERNET_DISP_PESSOAIS','TP_REDE_LOCAL', 'IN_BANDA_LARGA',
     'IN_MATERIAL_PED_MULTIMIDIA', 'IN_RESERVA_RENDA', 'IN_RESERVA_PPI','IN_RESERVA_PUBLICA', 'IN_EXAME_SELECAO',
     'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA', 'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA','IN_EQUIP_LOUSA_DIGITAL',
     'IN_EQUIP_MULTIMIDIA']
for a in q:
    print(a)
    print(enem_escolas[a].unique())

ind_rede
[0. 1.]
ind_concorrente
[nan  1.]
IN_DESKTOP_ALUNO
[nan  1.  0.]
IN_COMP_PORTATIL_ALUNO
[nan  0.  1.]
IN_TABLET_ALUNO
[nan  0.  1.]
IN_INTERNET
[ 1.  0. nan]
IN_INTERNET_ALUNOS
[nan  0.  1.]
IN_INTERNET_ADMINISTRATIVO
[nan  1.  0.]
IN_INTERNET_APRENDIZAGEM
[nan  0.  1.]
IN_INTERNET_COMUNIDADE
[nan  0.  1.]
IN_ACESSO_INTERNET_COMPUTADOR
[nan  0.  1.  9.]
IN_ACES_INTERNET_DISP_PESSOAIS
[nan  0.  1.  9.]
TP_REDE_LOCAL
[nan  0.  3.  1.  2.  9.]
IN_BANDA_LARGA
[ 1.  0. nan]
IN_MATERIAL_PED_MULTIMIDIA
[nan  9.  1.  0.]
IN_RESERVA_RENDA
[nan  1.  0.]
IN_RESERVA_PPI
[nan  1.  0.]
IN_RESERVA_PUBLICA
[nan  1.  0.]
IN_EXAME_SELECAO
[nan  0.  1.  9.]
IN_BIBLIOTECA
[ 1.  0. nan]
IN_BIBLIOTECA_SALA_LEITURA
[ 1. nan  0.]
IN_LABORATORIO_CIENCIAS
[ 1.  0. nan]
IN_LABORATORIO_INFORMATICA
[ 1.  0. nan]
IN_EQUIP_LOUSA_DIGITAL
[nan  0.  1.]
IN_EQUIP_MULTIMIDIA
[ 1.  0. nan]


In [80]:
q = [ 'ind_rede', 'ind_concorrente','IN_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO','IN_TABLET_ALUNO', 'IN_INTERNET',
     'IN_INTERNET_ALUNOS', 'IN_INTERNET_ADMINISTRATIVO','IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_COMUNIDADE',
     'IN_ACESSO_INTERNET_COMPUTADOR', 'IN_ACES_INTERNET_DISP_PESSOAIS', 'IN_BANDA_LARGA',
     'IN_MATERIAL_PED_MULTIMIDIA', 'IN_RESERVA_RENDA', 'IN_RESERVA_PPI','IN_RESERVA_PUBLICA', 'IN_EXAME_SELECAO',
     'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA', 'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA','IN_EQUIP_LOUSA_DIGITAL',
     'IN_EQUIP_MULTIMIDIA']
for a in q:
    enem_escolas[a].fillna('Não', inplace = True)
    enem_escolas[a].replace(to_replace = 0, value = 'Não', inplace = True)
    enem_escolas[a].replace(to_replace = 1, value = 'Sim', inplace = True)
    enem_escolas[a].replace(to_replace = 9, value = 'Não informado', inplace = True)

In [81]:
q = [  'ind_rede', 'ind_concorrente','IN_DESKTOP_ALUNO', 'IN_COMP_PORTATIL_ALUNO','IN_TABLET_ALUNO', 'IN_INTERNET',
     'IN_INTERNET_ALUNOS', 'IN_INTERNET_ADMINISTRATIVO','IN_INTERNET_APRENDIZAGEM', 'IN_INTERNET_COMUNIDADE',
     'IN_ACESSO_INTERNET_COMPUTADOR', 'IN_ACES_INTERNET_DISP_PESSOAIS', 'IN_BANDA_LARGA',
     'IN_MATERIAL_PED_MULTIMIDIA', 'IN_RESERVA_RENDA', 'IN_RESERVA_PPI','IN_RESERVA_PUBLICA', 'IN_EXAME_SELECAO',
     'IN_BIBLIOTECA', 'IN_BIBLIOTECA_SALA_LEITURA', 'IN_LABORATORIO_CIENCIAS', 'IN_LABORATORIO_INFORMATICA','IN_EQUIP_LOUSA_DIGITAL',
     'IN_EQUIP_MULTIMIDIA']
for a in q:
    print(a)
    print(enem_escolas[a].unique())

ind_rede
['Não' 'Sim']
ind_concorrente
['Não' 'Sim']
IN_DESKTOP_ALUNO
['Não' 'Sim']
IN_COMP_PORTATIL_ALUNO
['Não' 'Sim']
IN_TABLET_ALUNO
['Não' 'Sim']
IN_INTERNET
['Sim' 'Não']
IN_INTERNET_ALUNOS
['Não' 'Sim']
IN_INTERNET_ADMINISTRATIVO
['Não' 'Sim']
IN_INTERNET_APRENDIZAGEM
['Não' 'Sim']
IN_INTERNET_COMUNIDADE
['Não' 'Sim']
IN_ACESSO_INTERNET_COMPUTADOR
['Não' 'Sim' 'Não informado']
IN_ACES_INTERNET_DISP_PESSOAIS
['Não' 'Sim' 'Não informado']
IN_BANDA_LARGA
['Sim' 'Não']
IN_MATERIAL_PED_MULTIMIDIA
['Não' 'Não informado' 'Sim']
IN_RESERVA_RENDA
['Não' 'Sim']
IN_RESERVA_PPI
['Não' 'Sim']
IN_RESERVA_PUBLICA
['Não' 'Sim']
IN_EXAME_SELECAO
['Não' 'Sim' 'Não informado']
IN_BIBLIOTECA
['Sim' 'Não']
IN_BIBLIOTECA_SALA_LEITURA
['Sim' 'Não']
IN_LABORATORIO_CIENCIAS
['Sim' 'Não']
IN_LABORATORIO_INFORMATICA
['Sim' 'Não']
IN_EQUIP_LOUSA_DIGITAL
['Não' 'Sim']
IN_EQUIP_MULTIMIDIA
['Sim' 'Não']


In [82]:
enem_escolas['TP_REDE_LOCAL'].unique()

array([nan,  0.,  3.,  1.,  2.,  9.])

In [83]:
a = 'TP_REDE_LOCAL'
enem_escolas[a].fillna('Não', inplace = True)
enem_escolas[a].replace(to_replace = 0, value = 'Não', inplace = True) ## Não há rede local interligando computadores
enem_escolas[a].replace(to_replace = 1, value = 'Sim', inplace = True) ## A cabo
enem_escolas[a].replace(to_replace = 2, value = 'Sim', inplace = True) ## Wireless
enem_escolas[a].replace(to_replace = 3, value = 'Sim', inplace = True) ## A cabo e Wireless
enem_escolas[a].replace(to_replace = 9, value = 'Não informado', inplace = True)

In [84]:
enem_escolas['TP_REDE_LOCAL'].unique()

array(['Não', 'Sim', 'Não informado'], dtype=object)

In [85]:
q = ['QT_PROF_PEDAGOGIA','QT_TABLET_ALUNO', 'QT_PROF_COORDENADOR', 'QT_EQUIP_LOUSA_DIGITAL', 'QT_DESKTOP_ALUNO',
    'QT_COMP_PORTATIL_ALUNO','QT_PROF_PSICOLOGO', 'QT_EQUIP_MULTIMIDIA' ]
for a in q:
    enem_escolas[a].fillna(0, inplace = True)

In [86]:
vazios = pd.DataFrame({'Tipos':enem_escolas.dtypes, 'NaN':enem_escolas.isna().sum(),'Total':enem_escolas.count()}).sort_values('NaN', ascending = False)

In [87]:
vazios[vazios['NaN']>0]

Tipos     NaN   Total
NU_NOTA_MT       float64  106628  523034
NU_NOTA_CN       float64  102232  527430
NU_NOTA_LC       float64   92481  537181
NU_NOTA_CH       float64   88085  541577
NU_NOTA_REDACAO  float64   74334  555328
NU_NOTA_COMP5    float64   74334  555328
NU_NOTA_COMP4    float64   74334  555328
NU_NOTA_COMP3    float64   74334  555328
NU_NOTA_COMP1    float64   74334  555328
NU_NOTA_COMP2    float64   74334  555328
Unnamed: 0       float64     478  629184
CO_MUNICIPIO     float64     478  629184
NO_ENTIDADE       object     478  629184
CO_ENTIDADE      float64     478  629184
NU_ANO_CENSO     float64     478  629184
NU_IDADE         float64      16  629646

In [88]:
enem_escolas.dropna(axis = 0, how = 'all', inplace=True, subset= ['CO_ENTIDADE'])
enem_escolas.dropna(axis = 0, how = 'all', inplace=True, subset= [ 'NU_IDADE'])

In [89]:
vazios = pd.DataFrame({'Tipos':enem_escolas.dtypes, 'NaN':enem_escolas.isna().sum(),'Total':enem_escolas.count()}).sort_values('NaN', ascending = False)

In [90]:
vazios[vazios['NaN']>0]

Tipos     NaN   Total
NU_NOTA_MT       float64  106511  522657
NU_NOTA_CN       float64  102117  527051
NU_NOTA_LC       float64   92374  536794
NU_NOTA_CH       float64   87980  541188
NU_NOTA_REDACAO  float64   74236  554932
NU_NOTA_COMP5    float64   74236  554932
NU_NOTA_COMP4    float64   74236  554932
NU_NOTA_COMP3    float64   74236  554932
NU_NOTA_COMP2    float64   74236  554932
NU_NOTA_COMP1    float64   74236  554932

In [91]:
enem_escolas.to_csv(path_enem+'base_enem_completa.csv', sep = ';', encoding = 'ISO-8859-1', index = None)